Setup mailserver & configure mediawiki to use it 💌
RopeWiki/app pull request #26
Opened 2023-05-14 08:00 UTC by hcooper

- Setup a postfix relay for local containers.
 - Make mediawiki use it for sending mail.
  
 More details in `README.md`, including what needs to be done next for spam filtering.

2023-05-18 03:40 UTC, BenjaminPelletier commented on docker-compose.yaml
> +      - POSTFIX_myhostname=ropewiki.com  # who we identify ourselves as to clients
Can we pull this from the config like the other containers?

I'm not sure what a good default would be, but we probably don't want dev instances accidentally representing themselves as ropewiki.com

```suggestion
      - POSTFIX_myhostname=${WG_HOSTNAME:-localhost}  # who we identify ourselves as to clients
```

2023-05-18 03:40 UTC, BenjaminPelletier commented on docker-compose.yaml
> +      - POSTFIX_mynetworks=172.0.0.0/8  # which clients we will relay traffic for
Are we sure this is correct?

```
root@ropewiki:/rw/app# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' prod_ropewiki_db_1
172.19.0.2
root@ropewiki:/rw/app# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' prod_ropewiki_webserver_1
172.19.0.3
root@ropewiki:/rw/app# docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' prod_ropewiki_reverse_proxy_1
172.19.0.4
```

```
bjp@minis-server:/rw/app$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minis_ropewiki_db_1
172.18.0.2
bjp@minis-server:/rw/app$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minis_ropewiki_webserver_1
172.18.0.3
bjp@minis-server:/rw/app$ docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' minis_ropewiki_reverse_proxy_1
172.18.0.4
```

2023-05-18 03:40 UTC, BenjaminPelletier commented on mailserver/README.md
> +TODO:
Could we elaborate on what needs to be done for these so the procedure can be applied to a dev deployment to verify functionality?

2023-05-22 20:02 UTC, hcooper commented on mailserver/README.md
> +TODO:
I'll expand the docs but it's essentially just send an email from the site (e.g. click password reset).

However note that most domestic ISPs will block tcp port 25 outbound, so testing from home will likely never work (the attempt will still appear in the mailserver logs though).

2023-05-22 20:02 UTC, hcooper commented on docker-compose.yaml
> +      - POSTFIX_mynetworks=172.0.0.0/8  # which clients we will relay traffic for
I'm sure this is correct :-) What problem are you seeing? `172.0.0.0/8` is `172.0.0.0 -> 172.255.255.255`

(To be pedantic I should change that to the slightly more constrained `172.16.0.0/12` range. Strictly that's the class-B ip range, and the range docker uses by default).

This is also somewhat redundant as this service will not be exposed to the internet anyhow, so only local traffic will reach it regardless. But it's a good second layer of defense in case of the firewall being accidentally opened.

2023-05-22 20:05 UTC, hcooper commented on docker-compose.yaml
> +      - POSTFIX_myhostname=ropewiki.com  # who we identify ourselves as to clients
The domain in this case is just a "hello" message to clients (for their logs). It doesn't extend meaning any further to the rest of the process (e.g. won't influence which instance clients connect to).

2023-05-23 07:03 UTC, BenjaminPelletier requested changes
I would like to approve this PR after successfully receiving an email from a dev site deployment (using a GCP VM to clear any residential limitations).  After deploying a copy of the site including this PR, email fails to send with the following error:

```
$ docker container exec -it gcpdev_ropewiki_mailserver_1 mailq
-Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
AD99D4D856     1177 Tue May 23 06:55:44  admin@ropewiki.com
(connect to alt2.gmail-smtp-in.l.google.com[173.194.219.26]:25: Connection timed out)
                                         REDACTED@gmail.com

-- 1 Kbytes in 1 Request.
```

(note that the deployment is configured to use a different domain than ropewiki.com)

2023-05-23 07:04 UTC, BenjaminPelletier commented on docker-compose.yaml
> +      - POSTFIX_myhostname=ropewiki.com  # who we identify ourselves as to clients
Even if it's just a log message, it seems like we'd want the most correct value here, which is easily available with ${WG_HOSTNAME}.  Is there a reason to keep it as ropewiki.com?

2023-05-23 08:50 UTC, hcooper commented
> After deploying a copy of the site including this PR, email fails to send with the following error:
> 
> ```
> $ docker container exec -it gcpdev_ropewiki_mailserver_1 mailq
> -Queue ID-  --Size-- ----Arrival Time---- -Sender/Recipient-------
> AD99D4D856     1177 Tue May 23 06:55:44  admin@ropewiki.com
> (connect to alt2.gmail-smtp-in.l.google.com[173.194.219.26]:25: Connection timed out)
>                                          REDACTED@gmail.com
> 
> -- 1 Kbytes in 1 Request.
> ```

Yup, that's what a smtp block looks like. I've never used GCP, but the their docs say they block outbound tcp/25:

- https://cloud.google.com/firewall/docs/firewalls#blockedtraffic
- https://cloud.google.com/compute/docs/tutorials/sending-mail

...

Ah *crap*. Researching further it's seemingly the default for most hosting providers now too (and like gcp many just say "no"). This is much more locked down than just a few years ago. (Digital ocean say they also block 25 now, but maybe my VMs are grandfathered in to the old rules). Think we might need to switch to plan-B and use a 3rd party relay - especially if you want the level of dynamic deployment you've described. (The global anti-spam system is highly anti-dynamic. It wants static IPs, pre generated keys, matching DNS, etc).

I'll re-work this to code to relay via the ropewiki gmail account (I'll need the password at some point), which shouldn't take long. Then after I can research alternative relays (e.g. ones which will let you set the From: address, which on gmail is fixed to the account's address).

2023-05-23 08:51 UTC, closed without merging